### ISSUE TITLE
UNSELECT_TOOL does not set the current tool to none/-1

### ISSUE THREAD

**Issue by HAuser1234** [viesturz/klipper-toolchanger#10]
When running UNSELECT_TOOL the tool gets correctly unloaded, but the printer does not remember this action. Example:

T1 -> picks up tool one
UNSELECT_TOOL 
T1 -> message: tool already selected (but it isnt!)

Could you fix this bug ?

Best Regards

**Comment by viesturz** [comment]
Thanks, looking into this.
