### ISSUE TITLE
crash_mintime not doing anything? 

### ISSUE THREAD

**Issue by Martorias** [viesturz/klipper-toolchanger#12]
It seems the crash detection will instantly fire the crash_gcode regardless of what crash_mintime is set to.
I added some debug and could see that the mintime parameter gets pulled from config but even with it set to 5 (seconds?) it's instant.
I don't know enough about the klipper reactor and lambda stuff to troubleshoot more deeply myself :-(

Edit: I assume, from reading your comment, the idea is that if the probe triggers then untriggers between now and now+mintime it should return without firing the gcode stuff?

**Comment by viesturz** [comment]
Hi, thanks for the report. I recall it not working, but never got around to
finding the reason.
Will take another shot.

**Comment by Martorias** [comment]
Awesome, just tested and can confirm the small change fixed it. Thanks!
