### ISSUE TITLE
Latest klipper version breaks compatability

### ISSUE THREAD

**Issue by bmyonatan** [viesturz/klipper-toolchanger#19]
After updating klipper to the latest version (commit d4bae4dffe8d3996ed1b1dd8f5230a062ae3d033) I received the following error:
` 'ToolProbe' object has no attribute 'probe_offsets'`

reverting back to commit 7b490f3ec1d3f0477b90c74d96f51ba1fb457a46 resolves that error

**Comment by viesturz** [comment]
Thanks for heads up, that is a big refactor. Investigating how to migrate...
